### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Jianghanxiao/RoboEXP#1]
Hello, I am reading your paper and would like to examine how you implemented some aspects. Under what license is this project released under ? Thank you.

**Comment by Jianghanxiao** [comment]
Hi, thanks for the interest in our project and thanks for the reminder about the license! I will check with other authors and try to reply ASAP.

**Comment by Jianghanxiao** [comment]
We have added the MIT license. Thanks again for asking!
